id: I2F246A26
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:44:11+00:00'
last_modified: '2022-06-07T15:04:48.459164+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28845
  title: བོད་ཀྱི་རྩིས་རིག་ཀུན་འདུས་ཆེན་མོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    747E:
      image_group_id: I4715
      title: ''
      total_pages: 678
      order: 1
      base_file: 747E.txt
    0998:
      image_group_id: I4716
      title: ''
      total_pages: 846
      order: 2
      base_file: 0998.txt
    8D58:
      image_group_id: I4717
      title: ''
      total_pages: 774
      order: 3
      base_file: 8D58.txt
    3C38:
      image_group_id: I4718
      title: ''
      total_pages: 798
      order: 4
      base_file: 3C38.txt
    9C44:
      image_group_id: I4719
      title: ''
      total_pages: 814
      order: 5
      base_file: 9C44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
