id: P001767
initial_creation_type: ocr
source_metadata:
  id: bdr:W28845
  title: བོད་ཀྱི་རྩིས་རིག་ཀུན་འདུས་ཆེན་མོ
  author: ''
  volumes:
    f78e91494c1546f9a6686ab8765e7018:
      image_group_id: I4715
      title: ''
      volume_number: 1
      total_pages: 678
    085873841fa649799ed610ed596fbbde:
      image_group_id: I4716
      title: ''
      volume_number: 2
      total_pages: 846
    fc840d42af62430283204a028b69c3d1:
      image_group_id: I4717
      title: ''
      volume_number: 3
      total_pages: 774
    8189d104b5aa488d89b9254b877beb71:
      image_group_id: I4718
      title: ''
      volume_number: 4
      total_pages: 798
    de8bf8bc14d0463396197c682a2f5daa:
      image_group_id: I4719
      title: ''
      volume_number: 5
      total_pages: 814
